<div id="anchor-content" class="middle">
	<div id="page:main-container">
	
	<?php if(isset($_SESSION['message'])){ ?>
       	<div id="messages"><ul class="messages"><li class="success-msg"><ul><li><?php echo $_SESSION['message']?></li></ul></li></ul></div>
	<?php } ?>
        <div class="content-header" style="visibility: visible;">
    	<h3 class="icon-head head-system-account">EmailBrain</h3> 
		<?php $_key=explode('/',$_SERVER['REQUEST_URI']);$c=count($_key);$_key=$_key[$c-2];?>   
		<p class="form-buttons">
			<button style="" onclick="setLocation(window.location.href)" class="scalable " type="button" id="id_<?php echo $_key?>"><span>Reset</span></button>
			<button style="" onclick="editForm.submit();" class="scalable save" type="button" id="id_<?php echo $_key?>"><span>Save Account</span></button>
		
		</p>
	</div>
	<?php $readonly=isset($_SESSION['mailinglist'])?' readonly="yes" ':'';?>
	
	<div class="entry-edit">
	
		<form id="edit_form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>"><div><input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" /></div><div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend">Account Information</h4>
    	<div class="form-buttons"></div>
	</div>
    <div id="base_fieldset" class="fieldset ">
    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
            <tbody>
			  <tr>
        <td class="label"><label for="userame">EmailBrain Domain <span class="required">*</span></label></td>
    <td class="value">
        <input <?php echo $readonly?> type="text" class=" input-text required-entry" title="Enter EmailBrain Domain" value="<?php echo isset($_SESSION['EmailAccount'])?$_SESSION['EmailAccount'][0][domain]:''?>" name="domain" id="domain">            </td>
    </tr>
                <tr>
        <td class="label"><label for="userame">EmailBrain Username <span class="required">*</span></label></td>
    <td class="value">
        <input <?php echo $readonly?> type="text" class=" input-text required-entry" title="User Name" value="<?php echo isset($_SESSION['EmailAccount'])?$_SESSION['EmailAccount'][0][username]:''?>" name="username" id="api_user">            </td>
    </tr>
<tr>
        <td class="label"><label for="firstname">EmailBrain Password <span class="required">*</span></label></td>
    <td class="value">
        <input <?php echo $readonly?> type="password" class=" input-text required-entry" title="Password" value="<?php echo isset($_SESSION['EmailAccount'])?$_SESSION['EmailAccount'][0][password]:''?>" name="password" id="firstname">            </td>
    </tr>
<?php if($_SESSION['mailinglist']):?>
<tr>
	<td class="label"><label for="firstname">EmailBrain Malling List</label></td>
	<td class="value">
	<?php echo $_SESSION['mailinglist']?>
    </td>	
</tr>
</tr>
<!-----<tr>
	<td class="label"><label for="firstname">EmailBrain Dataset</label></td>
	<td class="value">
	<?php echo $_SESSION['dataset']?>
    </td>	
</tr>----->
<?php  endif; ?>
            </tbody>
        </table>
            </div>
        </div>
</form></div>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '');
</script>
                        </div>
        </div>
<?php unset($_SESSION['message'])?>	
<?php unset($_SESSION['EmailAccount'])?>
<?php unset($_SESSION['mailinglist'])?>
<?php unset($_SESSION['dataset'])?>		